"""Initial migration

Revision ID: 8882b7d1d63f
Revises: 
Create Date: 2026-04-13 12:59:26.372368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8882b7d1d63f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaking_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('address', sa.JSON(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('duration_in_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaking_requests_id'), 'speaking_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaking_requests_id'), table_name='speaking_requests')
    op.drop_table('speaking_requests')
    # ### end Alembic commands ###
